brew 'awscli'
brew 'curl'
brew 'ffmpeg'
brew 'git'
brew 'go'
brew 'heroku-toolbelt'
brew 'hub'
brew 'jq'
brew 'mackup'
brew 'mas'
brew 'packer'
brew 'shellcheck'
brew 'terraform'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'youtube-dl'

cask 'adobe-photoshop-lightroom'
cask 'airserver'
cask 'arq'
cask 'atom'
cask 'beamer'
cask 'docker'
cask 'dropbox'
cask 'evernote'
cask 'geekbench'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-photos-backup'
cask 'iterm2'
cask 'kindle'
cask 'microsoft-office'
cask 'musicbrainz-picard'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'transmission'
cask 'tunnelblick'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'whatsapp'
cask 'xld'

mas '1Password', id: 443987910
mas 'Parcel', id: 639968404
mas 'Pocket', id: 568494494
mas 'Tweetbot', id: 557168941
